Ticket 1
simyara/nodjs-hello-world pull request #5
Opened 2017-06-02 14:29 UTC by simyara

2017-06-05 14:26 UTC, ikryvanos requested changes

2017-06-05 14:26 UTC, satamail commented on index.js
> +app.use(function* (next) {
Please, remove excess middlewares

2017-06-06 06:48 UTC, ikryvanos approved these changes

2017-06-06 06:51 UTC, Alex4Max commented on actions/allPictures.js
> +"use strict";
Maybe it's better to leave one empty string after "use strict" to increase readability?

2017-06-06 06:51 UTC, Alex4Max approved these changes
👍

2017-06-06 06:53 UTC, merged